[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[edge_functions]]
  function = "og-physician"
  path = "/team/dr-*"
